name: portfolio
description: "A new Flutter web project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1

  # Web Packages
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  go_router: ^17.0.0
  carousel_slider: ^5.1.1
  sliver_tools: ^0.2.12
  vector_math: ^2.2.0

  # Animation Packages
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  shimmer_animation: ^2.2.2

  # Utility Packages
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  cached_network_image: ^3.4.1

  # State management Package
  fpdart: ^1.2.0
  provider: ^6.1.5+1
  get_it: ^9.0.5
  equatable: ^2.0.7

  # Backend Package
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Icons
  font_awesome_flutter: ^10.10.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  build_runner: ^2.10.4


flutter:
  uses-material-design: true

  assets:
    - assets/home/hero_section/
    - assets/home/icon/
    - assets/home/projects/